const FETCH_AUTH = "FETCH_AUTH"
const FETCH_AUTH_SUCCESS = "FETCH_AUTH_SUCCESS"
const FETCH_AUTH_FAIL = "FETCH_AUTH_FAIL"

const LOGIN = "LOGIN"
const LOGIN_SUCCESS = "LOGIN_SUCCESS"
const LOGIN_FAIL = "LOGIN_FAIL"

const SIGNUP = "SIGNUP"
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
const SIGNUP_FAIL = "SIGNUP_FAIL"

const REDIRECT_NOT_AUTH = "REDIRECT_NOT_AUTH"
const REDIRECT_AUTH = "REDIRECT_AUTH"
const REDIRECT_NOT_ADMIN = "REDIRECT_NOT_ADMIN"

const LOGOUT = "LOGOUT"
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
const LOGOUT_FAIL = "LOGOUT_FAIL"

export {
    FETCH_AUTH,
    FETCH_AUTH_SUCCESS,
    FETCH_AUTH_FAIL,
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    SIGNUP,
    SIGNUP_SUCCESS,
    SIGNUP_FAIL,
    REDIRECT_NOT_AUTH,
    REDIRECT_AUTH,
    REDIRECT_NOT_ADMIN,
    LOGOUT,
    LOGOUT_SUCCESS,
    LOGOUT_FAIL
}
