const FETCH_POSTS = "FETCH_POSTS"
const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS"
const FETCH_POSTS_FAIL = "FETCH_POSTS_FAIL"

const FILTER_POSTS = "FILTER_POSTS"
const FILTER_POSTS_SUCCESS = "FILTER_POSTS_SUCCESS"

const CREATE_POST = "CREATE_POST"
const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
const CREATE_POST_FAIL = "CREATE_POST_FAIL"

const FETCH_POST = "FETCH_POST"
const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS"
const FETCH_POST_FAIL = "FETCH_POST_FAIL"

const FETCH_POST_EDITTING = "FETCH_POST_EDITTING"
const FETCH_POST_EDITTING_SUCCESS = "FETCH_POST_EDITTING_SUCCESS"
const FETCH_POST_EDITTING_FAIL = "FETCH_POST_EDITTING_FAIL"

const UPDATE_POST = "UPDATE_POST"
const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS"
const UPDATE_POST_FAIL = "UPDATE_POST_FAIL"

const FETCH_PROFILE = "FETCH_PROFILE"
const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS"
const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL"

const DELETE_POST = "DELETE_POST"
const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
const DELETE_POST_FAIL = "DELETE_POST_FAIL"

const FETCH_POST_RE = "FETCH_POST_RE"
const FETCH_POST_RE_SUCCESS = "FETCH_POST_RE_SUCCESS"
const FETCH_POST_RE_FAIL = "FETCH_POST_RE_FAIL"

export {
    FETCH_POSTS,
    FETCH_POSTS_SUCCESS,
    FETCH_POSTS_FAIL,
    FILTER_POSTS,
    FILTER_POSTS_SUCCESS,
    CREATE_POST,
    CREATE_POST_SUCCESS,
    CREATE_POST_FAIL,
    FETCH_POST,
    FETCH_POST_SUCCESS,
    FETCH_POST_FAIL,
    FETCH_POST_EDITTING,
    FETCH_POST_EDITTING_SUCCESS,
    FETCH_POST_EDITTING_FAIL,
    UPDATE_POST,
    UPDATE_POST_SUCCESS,
    UPDATE_POST_FAIL,
    FETCH_PROFILE,
    FETCH_PROFILE_SUCCESS,
    FETCH_PROFILE_FAIL,
    DELETE_POST,
    DELETE_POST_SUCCESS,
    DELETE_POST_FAIL,
    FETCH_POST_RE,
    FETCH_POST_RE_SUCCESS,
    FETCH_POST_RE_FAIL
}
